services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
  etl:
    build: .
    depends_on:
      - db
